<h3 id="warning"><?=$this->mensagem?></h3>
<div id="menu">
<form action="<?=$this->url('application',['action'=>'buscar'])?>" method="post">
<a href="<?=$this->url('application',['action' => 'acessar'])?>">Acessar</a>
&nbsp;
<a href="<?=$this->url('application',['action' => 'cadastrar'])?>" >Cadastrar</a>
<label>Busca produtos:</label>
<input name="nome" value="" id="nome" type="text">
<input type="submit" value="Pesquisar" />
</form>
</div>
<table id="carrinho">
	<thead>
<?php
$titulos = array ('Codigo',
'Nome',
'Quantidade',
'Preço Unitário',
'Total',
'Editar',
'Excluir');
 
foreach ($titulos as $titulo)
{
 			echo '<th><button type="button">'.$this->escapeHtml($titulo).'</button></th>';
}
?>
</thead>
<?php
$somaTotal = 0;

foreach ($this->itens as $item)
{
 		$codigo = $item['id'];
 		$nome = $this->escapeHtml($item['nome']);
 		$quantidade = $this->escapeHtml($item['quantidade']);
 		$preco = $this->escapeHtml($item['valor']);

 		// Aqui foi necessário forçar o preço a assumir o formato americano
 		// porque ele não estava convertendo a moeda corretamente

 		$moeda = str_replace('.','',substr($preco,2));
 		$moeda = str_replace(',','.',$moeda);
 		$valorTotal = (float)$quantidade * (float)$moeda;
 		$totalItem = $this->escapeHtml(money_format('%.2n',$valorTotal));

		$editar = '<a href="./editar?id=' . $codigo.'">E</a>';
 		$excluir= '<a href="./excluir?id='.$codigo.'">X</a>';

 		$somaTotal += $valorTotal;

		$colunas= array($codigo,
 				$nome,
 				$quantidade,
 				$preco,
 				$totalItem,
 				$editar,
 				$excluir);

echo '<tr>';
 		foreach ($colunas as $coluna)
 		{
 			echo '<td>';
 			echo $coluna;
 			echo '</td>';

 		}

 		echo '</tr>';
}
?>
</table>
<?='R$'.money_format('%.2n',$somaTotal)?><br />
<a href="<?=$this->url('home')?>">Continuar comprando</a>
<a href="<?=$this->url('carrinho',['action'=>'fechar'])?>">Fechar compra</a>