<div id="menu">
<form action="<?=$this->url('application',['action'=>'buscar'])?>" method="post">
<?php
if (!isset($_SESSION['cliente']))
{
?>
<a href="<?= $this->url('application',['action' => 'acessar']) ?>" >Acessar</a>&nbsp;
<a href="<?= $this->url('application',['action' => 'cadastrar']) ?>" >Cadastrar</a>
<?php
}
else
{
?>
<a href="<?= $this->url('application', ['action' => 'logout']) ?>" >Sair</a>
<?php
}
?>
<label>Busca produtos:</label>
<input name="nome" value="" id="nome" type="text">
<input type="submit" value="Pesquisar" />
</form>
</div>
<h3 id="warning"><?=$this->mensagem?></h3>
<table id="carrinho">
	<thead>
<?php
$titulos = array ('Codigo',
'Nome',
'Quantidade',
'Preço Unitário',
'Total',
'Editar',
'Excluir');
 
foreach ($titulos as $titulo)
{
 			echo '<th><button type="button">'.$this->escapeHtml($titulo).'</button></th>';
}
?>
</thead>
<?php
$somaTotal = 0;

foreach ($this->itens as $item)
{
 		$codigo = $item['id'];
 		$nome = htmlentities($item['nome'],0,'iso-8859-1');
 		$quantidade = $this->escapeHtml($item['quantidade']);
 		$preco = $this->escapeHtml($item['valor']);

 		// Aqui foi necessário forçar o preço a assumir o formato americano
 		// porque ele não estava convertendo a moeda corretamente

 		$moeda = str_replace('.','',$preco); //$moeda = str_replace('.','',substr($preco,2));
 		$moeda = str_replace(',','.',$moeda);
 		$valorTotal = (float)$quantidade * (float)$moeda;
 		$totalItem = $this->escapeHtml(money_format('%.2n',$valorTotal));
 		
		/* $editar = '<a href=" . /editar?id=' . $codigo.'">E</a>';
 		$excluir= '<a href=" . /excluir?id=' . $codigo.'">X</a>'; */
 		
 		$excluir= "<a href='" . $this->url('carrinho',['action'=>'excluir','id'=>$item['id']]) . "'>X</a>";
 		
 		//$this->url('carrinho',['action'=>'comprar','id'=>$this->id]

 		$somaTotal += $valorTotal;

		$colunas= array($codigo,
 				$nome,
 				$quantidade,
 				$preco,
 				$totalItem,
 				$editar,
 				$excluir);

echo '<tr>';
 		foreach ($colunas as $coluna)
 		{
 			echo '<td>';
 			echo $coluna;
 			echo '</td>';

 		}
 		
 		echo '</tr>';
}
?>
</table>
<?='R$'.money_format('%.2n',$somaTotal)?><br />
<a href="<?=$this->url('home')?>">Continuar comprando</a>
<a href="<?=$this->url('carrinho',['action'=>'fechar'])?>">Fechar compra</a>