<center>
<form action="<?= $this->url('carrinho',['action'=>'alterar']) ?>" method="post">

<?php
if (isset($this->produtoSelecionado['id']))
{
echo '<b>Produto: '.$this->produtoSelecionado['nome'].'</b><br/>';
echo '<b>Preço: '.$this->produtoSelecionado['valor'].'</b><br/>';

?>

<input name="quantidade" value="<?=$this >produtoSelecionado['quantidade']?>" id="nome"type="text"/>
<input name="id" value="<?=$this->produtoSelecionado['id']?>" id="id"type="hidden"/>

<?php
}
?>
<input type="submit" name="alterar"value="Alterar"/>
</form>
</center>
<a href="<?=$this->url('carrinho')?>">Carrinho de compras</a>