<center>
<form action="/zend/acme/carrinho/alterar"
method="post">
<?php
if (isset($this->produtoSelecionado['id'])):
    echo '<b>Produto: '.$this->produtoSelecionado['nome'].'</b><br/>';
    echo '<b>Preço: '.$this->produtoSelecionado['valor'].'</b><br/>';
?>    
/* Quantidade */ 
    <input name="quantidade" value="<?=$this->produtoSelecionado['quantidade']?>" id="nome" type="text">
    <input name="id" value="<?=$this->produtoSelecionado['id']?>" id="id" type="hidden">
<?php
endif;
?>
<input type="submit" name="alterar"value="Alterar"/>
</form>
</center>
<a href="<?=$this->url('carrinho')?>">Carrinho de compras</a>