<center>
<form action="<?=$this->url('carrinho',['action'=>'gravar-compra'])?>" method="post">
<h2>Forma de pagamento:</h2>
<?=$this->escapeHtml('Boleto Bancário')?>
<input name="formaPagamento" value="boleto" id="formaPagamento" type="radio"/>
<?=$this->escapeHtml('Cartão de Crédito')?>
<input name="formaPagamento" value="cartao" id="formaPagamento" type="radio"/>
<input type="submit" name="gravar" value="Gravar"/>
</form>
</center>
<a href="<?= $this->url('carrinho') ?>">Carrinho de compras</a>