<?php
use Zend\View\Helper\HeadScript;

$content = file_get_contents(__DIR__ . '/incluir.js');
$this->headScript(HeadScript::SCRIPT)->appendScript($content);
?>

<?php
if (trim($this->mensagem) !== "") {
    ?>
<br>
<div class="row">
	<div class="col-lg-1"></div>
	<div class="col-lg-10 alert alert-danger alert-dismissible">
		<a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
		<h3 id="danger"><?=$this->mensagem?></h3>
	</div>
</div>
<?php
}
?>

<?php
$imgName = __DIR__ . '/../../../../../public/img/produtos/' . $this->produtoSelecionado['id'] . ".base64";
$img = '';
if (file_exists($imgName)){    
    $img = file_get_contents(__DIR__ . '/../../../../../public/img/produtos/' . $this->produtoSelecionado['id'] . ".base64");
}
?>

<div class="container">
	<h2>Alterar produto:</h2>
	
<form enctype="multipart/form-data" action="<?= $this->url('estoque',['action'=>'alterar','id' => $id])?>" method="post">
<div class="form-group">
	<input type="hidden" class="form-control" id="id" name="id"	value="<?=$this->produtoSelecionado['id']?>">
</div>
<div class="form-group col-lg-4">
	<input type="file" id="files" name="files[]" />
	<input type="hidden" name="imgb64" id="imgb64" />
	<output id="list"><img src="<?= $img ?>" class="img-responsive" alt="imagem não disponivel"></output>
</div>	

<div class="col-lg-4 col-lg-offset-4">	
<div class="form-group col-lg-12">
	<label for="nome">Nome:</label>
	<input name="nome" value="<?= $this->escapeHtml($this->produtoSelecionado['nome'])?>" class="form-control" id="nome" type="text" onkeypress="validarTamanhoDoNome()">
</div>
<?php
if ($this->alterarQuantidade):
?>					

<div class="form-group col-lg-12">
	<label for="quantidade">quantidade: <?= $this->escapeHtml($this->produtoSelecionado['quantidade'])?></label>
	<input type="number" class="form-control" name="quantidade" id="quantidade">
</div>
<?php
endif;
?>
<div class="form-group col-lg-12">
	<label for="preco">Preço:</label>
	<input class="form-control" name="preco" value="<?=$this->escapeHtml($this->produtoSelecionado['valor'])?>" id="preco" type="text"  required>
</div>
<div class="col-lg-4">
	<input class="form-control" type="submit" name="alterar" value="alterar" onkeypress="submitImg()"/>
</div>
</form> 
</div>

<a href="<?= $this->url('estoque',['action' => 'manter-produto'])?>" class="btn-floating btn-lg btn-default returnbtn">
<i class="glyphicon glyphicon-share-alt"></i>
</a>
</div>