<div class="container-fluid">
<?php
if (trim($this->mensagem) !== "") {
    ?>
<br>
	<div class="row">
		<div class="col-lg-1"></div>
		<div class="col-lg-10 alert alert-danger alert-dismissible">
			<a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
			<h3 id="danger"><?=$this->mensagem?></h3>
		</div>
	</div>
	<?php
}
?>
	<form class="form-inline"
		action="<?=$this->url('estoque',['action'=>'subtrair'])?>"
		method="post">
		<div class="row conteudo" style="height: 100%;">
			<div class="col-lg-offset-1 col-lg-7">
<?php
$imgName = __DIR__ . '/../../../../../public/img/produtos/' . $this->produtoSelecionado['id'] . ".base64";
$img = '';
if (file_exists($imgName)){
    $img = file_get_contents(__DIR__ . '/../../../../../public/img/produtos/' . $this->produtoSelecionado['id'] . ".base64");
}
?>
	<img src="<?= $img ?>" class="img-responsive" id="imgb"
					alt="imagem não disponivel">

			</div>
			<div class="col-lg-3">
				<div class="row">
        <?php
        if (isset($this->produtoSelecionado['id'])) {
            echo '<h2><b>Produto: ' . $this->escapeHtml($this->produtoSelecionado['nome']) . '</b></h2><hr>';
            echo '<h2><b>' . $this->escapeHtml('Preço:  R$') . $this->produtoSelecionado['valor'] . '</b></h2>';
            echo '<hr><h3><b>' . $this->escapeHtml('Posição de estoque:') . $this->produtoSelecionado['quantidade'] . '</b></h3>';
        }
        ?>
        
  <div class="form-group">
						<label for="quantidade">quantidade:</label> <input type="number"
							value="1" min="1" class="form-control" name="quantidade"
							id="quantidade">
					</div>
					<div class="form-group">
						<input type="hidden" class="form-control" id="id" name="id"
							value="<?=$this->produtoSelecionado['id']?>">
					</div>
					<br> <br>
					<div class="form-group">
						<button type="submit" class="btn btn-default" name="darbaixa">Dar
							baixa</button>
					</div>
				</div>
			</div>
	
	</form>
</div>
</div>
<div class="container col-lg-12"
	style="bottom: 70px; position: absolute;">
	<a href="<?= $this->url('estoque',['action'=>'manter-produto'])?>"
		class="btn-floating btn-lg btn-default"><i
		class="glyphicon glyphicon-share-alt"></i></a>
</div>