<?php
use Zend\View\Helper\HeadScript;

$content = file_get_contents(__DIR__ . '/incluir.js');
$this->headScript(HeadScript::SCRIPT)->appendScript($content);
?>

<?php
if(trim($this->mensagem) !==""){
?>
<br>
<div class="row">
<div class="col-lg-1"></div>
    <div class="col-lg-10 alert alert-danger alert-dismissible">
        <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
    	<h3 id="danger"><?=$this->mensagem?></h3>
    </div>
</div>
<?php
}
?>

<div class="container">
<h2>Inserir novo produto:</h2>
<form enctype="multipart/form-data" class="form-inline" action="<?= $this->url('estoque',['action'=>'incluir-produto']) ?>" method="post">
<div class="form-group">
    <label for="nome">Nome:</label>
    <input name="nome" class="form-control" id="nome" type="text" onkeypress="validarTamanhoDoNome()">
</div><br>
<div class="form-group"><br>
    <input type="file" id="files" name="files[]"/>
    <input type="hidden" name="imgb64" id="imgb64"/>
<output id="list"></output>

</div><br><br>
<div class="form-group">
    <input class="form-control" type="submit" name="incluir" value="Incluir" onkeypress="submitImg()"/>
</div>
</form><br>
<a href="<?= $this->url('estoque',['action' => 'manter-produto'])?>" class="btn-floating btn-lg btn-default"><i class="glyphicon glyphicon-share-alt"></i></a>
</div>