<h2 id="warning"><?=$this->mensagem?></h2>
<h2>Estoquista: <?=$this->cpf?></h2>
<table id="inventario">
<thead>
<?php
$titulos = array('Código',
 					'Nome',
 					'Quantidade',
 					'Preço Unitário',
 					'Dar entrada',
 					'Dar baixa',
 					'Excluir');
foreach ($titulos as $titulo)
{
 	echo '<th>'.$this->escape($titulo).'</th>';
}
?>

</thead>
<?php
$somaTotal = 0;

foreach ($this->itens as $item)
{
 				 	 	 	 		$codigo	 				 			= 										 	$item['id'];
 			  	 		 		$nome		 		 			 					= 							 	'<a
 	 		href="/zend/acme/estoque/nome?id='.$codigo.'">'.$this >escape($item['nome']).'</a>';
 					 	 	  			$quantidade 	 = $item['quantidade'];
 			 	 	 			 		$preco 							 		 												= 	 		'<a
 	 		href="/zend/acme/estoque/preco?id='.$codigo.'">'.$item['valor'].'
</a>';
 				 	 	  		$entrada					 		=  								'<a
 			 	href="/zend/acme/estoque/entrada?id='.$codigo.'">E</a>';
 		 		 	 	 	$baixa 					 		 	=  							'<a
 	 		href="/zend/acme/estoque/baixa?id='.$codigo.'">B</a>';
 			 		 	 	 	$excluir 		= 		 								'<a
 	 		href="/zend/acme/estoque/excluir?id='.$codigo.'">X</a>';
 			 		 	 	 	
 			 		 	 	 	$colunas = array($codigo,
 			 		 	 	 	    $nome,
 			 		 	 	 	    $quantidade,
 			 		 	 	 	    $preco,
 			 		 	 	 	    $entrada,
 			 		 	 	 	    $baixa,
 			 		 	 	 	    $excluir);
 			 		 	 	 	echo '<tr>';
 			 		 	 	 	
 			 		 	 	 	foreach ($colunas as $coluna)
 			 		 	 	 	{
 			 		 	 	 	    echo '<td>';
 			 		 	 	 	    echo $coluna;
 			 		 	 	 	    echo '</td>';
 			 		 	 	 	}
 			 		 	 	 	
 			 		 	 	 	echo '</tr>';
}
?> 	

</table>
<a href="/zend/acme/estoque/logout">Sair</a>