<div class="container-fluid">
<?php
if(trim($this->mensagem) !==""){
?>
<br>
<div class="row">
<div class="col-lg-1"></div>
    <div class="col-lg-10 alert alert-danger alert-dismissible">
        <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
    	<h3 id="danger"><?=$this->mensagem?></h3>
    </div>
</div>
<?php
}
?>
<h2>Estoquista: <?=$this->cpf?></h2>
<table id="inventario" class="table table-hover text-center">
<thead>
<?php
$titulos = array('Código',
 					'Nome',
 					'Quantidade',
 					'Preço Unitário',
 					'Dar entrada',
 					'Dar baixa',
 					'Excluir');
foreach ($titulos as $titulo)
{
 	echo '<th class="text-center">' . $this->escapeHtml($titulo) . '</th>';
}
?>

</thead>
<?php
$somaTotal = 0;
foreach ($this->itens as $item)
{
    $codigo = $item['id'];
    $nome = '<a href="' . $this->url('estoque',['action'=>'nome','id'=>$codigo]) . '" data-toggle="tooltip" data-placement="right auto" title="alterar nome">'.$item['nome'].'</a>';

    $quantidade = (empty($item['quantidade']) ? '0' : $item['quantidade']);
    
    $preco ='<a href="' . $this->url('estoque',['action'=>'preco','id'=>$codigo]) . '" data-toggle="tooltip" data-placement="right auto" title="alterar preço"> <b>R$ </b>'.(empty($item['valor']) ? '0' : $item['valor']).'</a>';
    
    $entrada ='<a href="' . $this->url('estoque',['action'=>'entrada','id'=>$codigo]) . '" data-toggle="tooltip" data-placement="right auto" title="entrada do produto"><i class="glyphicon glyphicon-plus"></i></a>';
    
    $baixa ='<a	href="' . $this->url('estoque',['action'=>'baixa','id'=>$codigo]) . '" data-toggle="tooltip" data-placement="right auto" title="baixa do produto"><i class="glyphicon glyphicon-minus"></i></a>';
    
    $excluir = '<a href="' . $this->url('estoque',['action'=>'excluir','id'=>$codigo]) . '"  data-toggle="tooltip" data-placement="right auto" title="excluir produto"><i class="glyphicon glyphicon-remove"></i></a>';

    $colunas = array(
        $codigo,
        $nome,
        $quantidade,
        $preco,
        $entrada,
        $baixa,
        $excluir
    );
    echo '<tr>';

    foreach ($colunas as $coluna) {
        echo '<td>';
        echo $coluna;
        echo '</td>';
    }

    echo '</tr>';
}
?> 	

</table><br>
	<div>
        <a href="<?= $this->url('estoque',['action' => 'logout'])?>" class="btn-floating btn-lg btn-default"><i class="glyphicon glyphicon-share-alt"></i></a>
        <a href="<?= $this->url('estoque',['action' => 'incluir'])?>" class="btn-floating btn-lg btn-default"><i class="glyphicon glyphicon-plus-sign"></i></a>
    </div>
<br><br><br><br>
</div>