<?php
if(trim($this->mensagem) !==""){
?>
<br>
<div class="row">
<div class="col-lg-1"></div>
    <div class="col-lg-10 alert alert-danger alert-dismissible">
        <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
    	<h3 id="danger"><?=$this->mensagem?></h3>
    </div>
</div>
<?php
}
?>

<div class="container">
<h2>Alterar preço do produto:</h2>
<form class="form-inline" action="<?= $this->url('estoque',['action'=>'alterar-preco'])?>" method="post">
<?php
if (isset($this->produtoSelecionado['id']))
{
?>
<div class="form-group">
<label for="preco">Preço:</label>
<input class="form-control" name="preco" value="<?=$this->escapeHtml($this->produtoSelecionado['valor'])?>" id="preco" type="text">
</div>
<div class="form-group">
<input name="id" value="<?=$this->produtoSelecionado['id']?>" id="id" type="hidden">
</div>
<?php
}
?>
<div class="form-group">
<input type="submit" name="alterarpreco" value="Alterar preço"/>
</div>

</form><br>
<a href="<?= $this->url('estoque',['action' => 'manter-produto'])?>" class="btn-floating btn-lg btn-default"><i class="glyphicon glyphicon-share-alt"></i></a>
</div>