<?php
if ($this->partialLoop()->getPartialCounter() % 2 !== 0):
?>
<tr>
<?php
endif;
?>
<td id="produto">
<?=htmlentities($this->nome,0,'iso-8859-1')?><br/>
<?=$this->escapeHtml($this->valor)?><br/>
<?=$this->escapeHtml('Quantidade disponível: ')?>
<?=$this->escapeHtml($this->quantidade)?><br/>
<a id="botao_comprar" href="<?=$this->url('carrinho',['action'=>'comprar','id'=>$this->id])?>">Comprar</a>
</td>
<?php
if ($this->partialLoop()->getPartialCounter() % 2 == 0):
?>
</tr>
<?php
endif;
?>