<?php
if ($this->partialLoop()->getPartialCounter() == 3):
?>
<div class="row">
<?php
endif;
?>
<div class="col-lg-4 card" id="card">
<?php
$img = file_get_contents(__DIR__ . '/../../../public/img/produtos/' . $this->id . ".base64");
?>

<a href="<?= $this->url('carrinho',['action'=>'detalhes','id'=> $this->id])?>">
<img src="<?= $img ?>" class="card-img-top" id="cardimg" alt="imagem não disponivel">
</a>
  <div class="card-body">
    <h3 class="card-title"><?=substr(htmlentities($this->nome,0,'UTF-8'), 0, 32)?><br/></h3>
    <p class="card-text"><?=$this->escapeHtml('Quantidade disponível: ')?>
    <?=$this->escapeHtml($this->quantidade)?></p>
    <p class="card-text">R$<?=$this->escapeHtml($this->valor)?></p>
    <a href="<?=$this->url('carrinho',['action'=>'comprar','id'=>$this->id])?>" class="btn btn-default">Comprar</a>
  </div>
</div>
<?php
if ($this->partialLoop()->getPartialCounter() == 3):
?>
</div>
<?php
endif;
?>