<?php
if ($this->partialLoop()->getPartialCounter() == 3):
?>
<div class="row">
<?php
endif;
?>
<div class="col-lg-4 card" id="card">
  <img src="img/produtos/produto.png" id="imagem" class="card-img-top" style="width: 18rem;" alt="imagem não disponivel">
  <div class="card-body">
    <h3 class="card-title"><?=substr(htmlentities($this->nome,0,'iso-8859-1'), 0, 32)?><br/></h3>
    <p class="card-text"><?=$this->escapeHtml('Quantidade disponível: ')?>
    <?=$this->escapeHtml($this->quantidade)?></p>
    <p class="card-text">R$<?=$this->escapeHtml($this->valor)?></p>
    <a href="<?=$this->url('carrinho',['action'=>'comprar','id'=>$this->id])?>" class="btn btn-default">Comprar</a>
  </div>
</div>
<?php
if ($this->partialLoop()->getPartialCounter() == 3):
?>
</div>
<?php
endif;
?>