<h3 id="warning"><?=$this->mensagem?></h3>
<center>
<form action="<?=$this->url('application',['action'=>'login'])?>" method="post">
<!-- <form action="/zend/acme/index/login" method="post"> -->
CPF:
<input name="cpf" value="" id="cpf" type="text">
e-mail:
<input name="email" value="" id="email" type="text">
senha:
<input name="senha" value="" id="senha" type="password">
<input type="submit" name="login" value="Login"/>
</form>
</center>
<a href="<?=$this->url('carrinho')?>">Carrinho de compras</a>