<center>
<form action="/zend/acme/carrinho/gravarCompra" method="post">
<h2>Forma de pagamento:</h2>
<?=$this->escape('Boleto Bancário')?>
<input name="formaPagamento" value="boleto" id="formaPagamento" type="radio"/>
<?=$this->escape('Cartão de Crédito')?>
<input name="formaPagamento" value="cartao" id="formaPagamento" type="radio"/>
<input type="submit" name="gravar" value="Gravar"/>
</form>
</center>
<a href="/zend/acme/carrinho">Carrinho de compras</a>