<div id="menu">
<form action="<?=$this->url('application')?>" method="post">
<?php
if (!isset($_SESSION['cliente']))
{
?>
<a href="<?= $this->url('application',['action' => 'acessar']) ?>" >Acessar</a>&nbsp;
<a href="<?= $this->url('application',['action' => 'cadastrar']) ?>" >Cadastrar</a>
<?php
}
else
{
?>
<a href="<?= $this->url('application', ['action' => 'logout']) ?>" >Sair</a>
<?php
}
?>
<label>Busca produtos:</label>
<input name="nome" value="" id="nome" type="text">
<input type="submit" value="Pesquisar" />
</form>
</div>
<table id="lista_de_produtos">
<?=$this->partialLoop('produtos.phtml',$this->produtos)?>
</table>

<!-- ir pro carrinho sem comprar nenhum produto
<a id="botao_comprar" href="<?=$this->url('carrinho',['action'=>'comprar'])?>">Comprar</a>
-->