<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="<?=$this->url('home')?>">Lojas Acme</a>
    </div>
    <form class="navbar-form navbar-right" action="<?=$this->url('application')?>" method="post">
      <div class="input-group">
        <input type="text" class="form-control" placeholder="" name="nome" id="nome">
        <div class="input-group-btn">
          <button class="btn btn-default" type="submit">
            <i class="glyphicon glyphicon-search"></i>
          </button>
        </div>
      </div>
    </form>
    <?php
        if (!isset($this->storage->cliente))
        {
        ?>
    <ul class="nav navbar-nav navbar-right">
      <li><a href="<?= $this->url('application',['action' => 'acessar']) ?>" >Acessar</a>&nbsp</li>
      <li><a href="<?= $this->url('application',['action' => 'cadastrar']) ?>" >Cadastrar</a></li>
    </ul>
    <?php
        }
        else
        {
    ?>
    <ul class="nav navbar-nav navbar-right">
      <li><a href="<?= $this->url('application', ['action' => 'logout']) ?>" >Sair</a></li>
    </ul>
    <?php
        }
    ?>    
  </div>
</nav>

<form action="<?=$this->url('application')?>" method="post">
	<div class="jumbotron container">
		<center><?=$this->partialLoop('produtos.phtml',$this->produtos)?></center>
	</div><br>
</form><br>

<!-- 
ir pro carrinho sem comprar nenhum produto
<a id="botao_comprar" href="<?=$this->url('carrinho',['action'=>'comprar'])?>">Comprar</a>
-->